[package]
name = "rust64"
version = "0.6.1"
authors = [ "Krzysztof Kondrak <krzysztof.kondrak@gmail.com>" ]
edition = "2021"

[dependencies]
minifb = "0.25"
rand = "0.8"
byteorder = "1.5"
enum_primitive = "0.1"
num = "0.1"


[target.'cfg(not(target_os = "redox"))'.dependencies]
sdl2 = "0.35.0"
